name: 'WordPress Plugin Deploy'
description: 'Deploy to the WordPress Plugin Repository'
author: '10up'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  generate-zip:
    description: 'Generate package zip file?'
    default: false
  commit-message:
    description: 'Use git last commit message if true, or "Update to version $VERSION from GitHub" if false else a resolvable command/text.'
    default: false
outputs:
  zip-path:
    description: 'Path to zip file'
    value: ${{ steps.deploy.outputs.zip-path }}
runs:
  using: 'composite'
  steps:
    - id: deploy
      env:
        INPUT_GENERATE_ZIP: ${{ inputs.generate-zip }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: ${{ github.action_path }}/deploy.sh
      shell: bash
