name: Automated Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@master
